name: client
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  # flutter sdk
  flutter:
    sdk: flutter

  # l10n & date format
  flutter_localizations:
    sdk: flutter
  intl: 0.18.1

  # packages
  cached_network_image: ^3.3.0
  flutter_hooks: ^0.20.3
  flutter_riverpod: ^2.4.8
  hooks_riverpod: ^2.4.8
  go_router: ^12.1.1
  riverpod: ^2.4.8
  gap: ^3.0.1
  quick_log: ^5.3.1
  rename_app: ^1.3.1
  animations: ^2.0.8
  flutter_native_splash: ^2.3.1
  flutter_animate: ^4.2.0
  flutter_screenutil: ^5.8.4
  equatable: ^2.0.5
  shared_preferences: ^2.2.0
  # dio
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  pinch_zoom: ^2.0.0
  flutter_svg: ^2.0.9
  material_symbols_icons: ^4.2711.0
  pluto_grid: ^7.0.2
  skeletonizer: ^1.0.1
  crypto: ^3.0.3
  get_secure_storage: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_lint: ^2.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_gen_runner: ^5.3.2
  build_runner: ^2.4.6

flutter_launcher_icons:
  image_path: "assets/logo/icon.png"
  windows:
    generate: true
    image_path: "assets/logo/icon.png"
    icon_size: 256 # min:48, max:256, default: 48

# Flutter gen configuration
flutter_gen:
  output: lib/assets/ # Optional (default: lib/gen/)
  # Optional
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
    - assets/icons/

  fonts:
    - family: DMSans
      fonts:
        # regular
        - asset: assets/fonts/DMSans/DMSans-Regular.ttf

        # light
        - asset: assets/fonts/DMSans/DMSans-Light.ttf
          weight: 300
        
        # medium
        - asset: assets/fonts/DMSans/DMSans-Medium.ttf
          weight: 500
        
        # semi bold
        - asset: assets/fonts/DMSans/DMSans-SemiBold.ttf
          weight: 600
        
        # bold
        - asset: assets/fonts/DMSans/DMSans-Bold.ttf
          weight: 700

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 800