# Generated by Django 4.2.8 on 2024-01-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="information",
            field=models.CharField(max_length=255),
        ),
    ]
