# Generated by Django 4.2.8 on 2024-01-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="rating",
            field=models.IntegerField(),
        ),
    ]
